### ISSUE TITLE
支持匠魂进化的恣意特性

### ISSUE THREAD

**Issue by mczph** [GlodBlock/DeepMobEvolution-Blood#11]
相关链接：https://www.mcmod.cn/item/312394.html

玩家提供的演示视频
https://github.com/GlodBlock/DeepMobEvolution-Blood/assets/103164772/f7b35d24-ab95-44a8-80a3-5c272c420f0f

**Comment by GlodBlock** [comment]
已添加https://github.com/GlodBlock/DeepMobEvolution-Blood/releases/tag/1.1.5-e
