### ISSUE TITLE
在使用电力的匠魂工具上优先使用电量

### ISSUE THREAD

**Issue by mczph** [GlodBlock/DeepMobEvolution-Blood#12]
相关特性：[电力装载](https://github.com/phantamanta44/tinkers-evolution/blob/1.12.2/src/main/java/xyz/phanta/tconevo/trait/TraitEnergized.java)，[通量注入](https://github.com/phantamanta44/tinkers-evolution/blob/1.12.2/src/main/java/xyz/phanta/tconevo/trait/ModifierFluxed.java)，[充能](https://github.com/phantamanta44/tinkers-evolution/blob/1.12.2/src/main/java/xyz/phanta/tconevo/trait/ic2/TraitElectric.java)

**Comment by GlodBlock** [comment]
已修复https://github.com/GlodBlock/DeepMobEvolution-Blood/releases/tag/1.1.6-e
