### ISSUE TITLE
Can you increase limits ?? 

### ISSUE THREAD

**Issue by ferreiraalex** [GlodBlock/DeepMobEvolution-Blood#8]
this
 @Config.Comment({
        "Max: 10,000",
        "Default: 128"
    })
    @Config.Name("RF tick cost of the Digital Agonizer")
    @Config.RangeInt(min = 1, max = 10000)
    public static int agonizerRFCost = 128;
    public static int getAgonizerRFCost() {
        return MathHelper.clamp(agonizerRFCost, 1, 10000);
    }

    @Config.Comment({
            "Max: 10,000",
            "Default: 256"
    })
    @Config.Name("RF tick cost of the Digital Will Injector")
    @Config.RangeInt(min = 1, max = 10000)
    public static int willInjectorRFCost = 256;
    public static int getWillInjectorRFCost() {
        return MathHelper.clamp(willInjectorRFCost, 1, 10000);

to this limits

general {
    B:"Allow multiple agonizers linked with one Altar"=false

    # Min: 1
    # Max: 2,147,483,647
    I:"Digital Agonizer Input RF a Tick"=2147483647

    # Min: 1
    # Max: 2,147,483,647
    I:"Digital Agonizer RF Storage Size"=2147483647

    # Min: 1
    # Max: 2,147,483,647
    I:"RF tick cost of the Digital Agonizer"=666666736

10 k its so small for huge modpack
thanks

**Comment by GlodBlock** [comment]
fixed in 1.1.4-e

**Comment by ferreiraalex** [comment]
Thank you so much
