### ISSUE TITLE
[Suggestions]Tinkers Addon also for Glitch Infused Ingot

### ISSUE THREAD

**Issue by mczph** [GlodBlock/DeepMobEvolution-Blood#9]
I have submitted an [issue](https://github.com/ThePansmith/DeepMobEvolution/issues/18) to [DeepMobEvolution](https://github.com/ThePansmith/DeepMobEvolution), but there seems to be no response. Although this is not suitable, can you add compatibility here?

**Comment by GlodBlock** [comment]
你最好直接去dc和作者私聊说一下，毕竟这个东西不是我mod加的，联动放我这里会很奇怪

**Comment by mczph** [comment]
那我觉得还是close了吧，毕竟dmebm提供了特性，可以自己用魔改写
